### ISSUE TITLE
is this currently maintained?

### ISSUE THREAD

**Issue by zahmadsaleem** [cityzenith/Revit2Gltf#2]
It would be great to know the known bugs/ missing features as well.

also how does this differ from  [McCulloughRT/Revit2glTF](https://github.com/McCulloughRT/Revit2glTF)

**Comment by lelandjobson** [comment]
Hey @zahmadsaleem ,

This is a new project and yes, its maintained. We could do better to provide more transparency on that.

McCullogh's differs in a few ways:
- It (McColloughs) doesn't support textured materials, we do. It requires some nasty, nasty code where you're shooting into the dark. Since I opened sourced this, you can see for yourself.
- It doesn't seem to be supported. 
- It uses revits exporter framework, which iterates through elements in the document and you do your export thing to write them in the file. We do not follow this method as the revit API sucks and the fewer ways to deal with it the better. So instead we use revit's FBX exporter, and Assimp to load the FBX after its created. This results in higher latency and much higher memory consumption, but on the other hand, the Revit -> FBX exporter is a well tested tool that more or less gives you everything you want. Same with Assimp, for the most part. We don't have to write any middleware classes for meshes / adapter for gltf ourselves. I've written middleware classes and all that stuff how other uses - it sucks ass. Better to use a third party library and call it day. It makes things a lot simpler, with the performance being a caveat.
- Element parameter data is exported to a separate file (JSON), not embedded in the gltf. I prefer geometry and data to live in separate places. You can rectify this simply in whatever application you choose.

**Comment by lelandjobson** [comment]
Some information about whats missing / caveats:
- We need to test it on a whole lot more models.
- Its slow, for large models.
- Its can crash on large models (bigger than 500 MB) as the memory footprint for the geometry is huge. Note that a 500 MB revit file leverages block instancing (families), so once you're converting every element into its own geo, that goes through the ceiling.
- Its only been tested on 2 versions of Revit - 2020 and 2016.
- You get a single GLTF, not by category
